### ISSUE TITLE
undefined methods

### ISSUE THREAD

**Issue by murtyk** [railslove/birthday#1]
sorry, I found the problem,

it should be s.dob_today?

Pls close this issue.

Thanks

I tried the following:
1.  added gem 'birthday', '~> 0.2.0' to gemfile
2. bundle install
3. added the following line to Student.rb:
   
   acts_as_birthday :dob
   
   ```
   dob is a date attribute in postgres
   ```
4. getting undefined method on:
   
   Student.birthday_today
   
   Student.first.birthday_today?

**Comment by blakerego** [comment]
Hi, I am also experiencing the same problem. Have there been any updates to this?

**Comment by bumi** [comment]
Hi,
can you provide the database schema for your model and I'm happy to look into this issue.

**Comment by blakerego** [comment]
create_table "users", :force => true do |t|
    t.string   "name"
    t.string   "email"
    t.string   "uid"
    t.datetime "created_at",   :null => false
    t.datetime "updated_at",   :null => false
    t.float    "score"
    t.string   "gender"
    t.datetime "dob"
  end

In the User model, I'm using -
acts_as_birthday :dob
